# https://github.com/mxcl/xcodebuild

name: Xcode Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    strategy:
      matrix:
        platform:
          - iOS
        xcode:
          - ^13
    runs-on: macos-latest
    steps:
      - use: mxcl/xcodebuild@v1
        with:
          xcode: ${{ matrix.xcode }}
          platform: ${{ matrix.platform }}
          action: build # default = `test`
          code-coverage: false # default = `false`
          warnings-as-errors: false # default = `false`
          configuration: debug # no default, ie. `xcodebuild` decides itself
